FROM python:3.9-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir paho-mqtt influxdb-client pymongo

# Copy application code
COPY processor/ .

# Command to run the processor
CMD ["python", "processor.py"]